spring:
  profiles:
    active: dev  
  rabbitmq:
    host: ${RABBIT_MQ_HOST:172.16.0.13}
    port: ${RABBIT_MQ_PORT:31352}
    username: ${RABBIT_MQ_USERNAME:user}
    password: ${RABBIT_MQ_PASSWORD:szwg%2020}
  redis:
    cluster:
      nodes:
        - 172.16.0.9:7000
        - 172.16.0.9:7001
        - 172.16.0.9:7002
        - 172.16.0.9:7003
        - 172.16.0.9:7004
        - 172.16.0.9:7005
    #host: ${REDIS_HOST:127.0.0.1}
    #port: ${REDIS_PORT:6379}
    #password: ${REDIS_PASSWORD:123}
    lettuce:
    #jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10      
        min-idle: 5

  #jwt密码
  #security:
   # oauth2:
    #  jwt:
     #   signingKey: 123456
  #cloud:
   # gateway:
    #  default-filters:
     #   - name: Retry
      #    args:
       #     retries: 3
        #    statuses: BAD_GATEWAY
        #- AddResponseHeader=X-Response-Default-Foo, Default-Bar
        #- name: RequestRateLimiter
        #  args:
        #    redis-rate-limiter.replenishRate: 2  #流速 每秒
         #   redis-rate-limiter.burstCapacity: 10   #令牌桶的容积
          #  rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
          #  key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean

jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  hidePackages: com.wenge.tbase.gateway
  local:
    # 默认永久本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    # 默认永久的远程缓存
    default:
      type: redis.lettuce
      #type: redis
      keyConvertor: fastjson    
      uri[0]: redis://172.16.0.9:7000/
      uri[1]: redis://172.16.0.9:7001/
      uri[2]: redis://172.16.0.9:7002/
      uri[3]: redis://172.16.0.9:7003/
      uri[4]: redis://172.16.0.9:7004/
      uri[5]: redis://172.16.0.9:7005/
      valueEncoder: kryo
      valueDecoder: kryo
      #poolConfig:
       # minIdle: 5
        #maxIdle: 1000
        #maxTotal: 2000
      #host: ${spring.redis.host}
      #port: ${spring.redis.port}
      #password: ${spring.redis.password}

#网关白名单，无需要签权url
#gate:
 # ignore:
  #  authentication:
   #   startWith: /oauth,/open,/v2/api-docs
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

#logging:
 # level:
  #  com.springboot.cloud: debug
  #  com.jalja.org.spring: debug
  #  #org.springframework.cloud.gateway: trace
 # path: logs/
 # file:
  #  max-size: 1GB