spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:10.148.25.24}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:admin}
    password: ${RABBIT_MQ_PASSWORD:admin%2020}
  redis:
    cluster:
      nodes:
        - 10.148.25.30:8001
        - 10.148.25.30:8002
        - 10.148.25.30:8003
        - 10.148.25.30:8004
        - 10.148.25.30:8005
        - 10.148.25.30:8006
    #host: ${REDIS_HOST:127.0.0.1}
    #port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:uBOWSBEo8N}
    lettuce:
    #jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10      
        min-idle: 5
    
  datasource:
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:10.148.25.11}:${DATASOURCE_PORT:3306}/am_gateway?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Hongkong
    username: ${DATASOURCE_USERNAME:wg_dba}
    password: ${DATASOURCE_PASSWORD:wg%2020}
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  
jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  hidePackages: com.wenge.tbase.gateway
  local:
    # 默认永久本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    # 默认永久的远程缓存
    default:
      type: redis.lettuce
      #type: redis
      keyConvertor: fastjson    
      uri[0]: redis://${spring.redis.password}@10.148.25.30:8001/
      uri[1]: redis://${spring.redis.password}@10.148.25.30:8002/
      uri[2]: redis://${spring.redis.password}@10.148.25.30:8003/
      uri[3]: redis://${spring.redis.password}@10.148.25.30:8004/
      uri[4]: redis://${spring.redis.password}@10.148.25.30:8005/
      uri[5]: redis://${spring.redis.password}@10.148.25.30:8006/
      valueEncoder: kryo
      valueDecoder: kryo

management:
  endpoints:
    web:
      exposure:
        include: '*'

#logging:
#  level:
#    com.springboot.cloud.gateway: debug
#    com.jalja.org.spring: debug
#  path: logs/
#  file:
#    max-size: 1GB
#mybatis-plus:
#  configuration:
#    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl